"""initial schema

Revision ID: 09febdbf1143
Revises: 0001_extensions
Create Date: 2026-10-07 19:45:26.690500
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '09febdbf1143'
down_revision: str | None = '0001_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_processing_job_key')
    )
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status', 'run_after'], unique=False)
    op.create_table('events',
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'CLUSTERING', 'VERIFYING', 'VERIFIED', 'EDITORIAL_REVIEW', 'PUBLISHED', 'UPDATING', 'ARCHIVED', 'UNVERIFIED', 'WAIT', name='event_status'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_country'), 'events', ['country'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('type', sa.Enum('rss', 'atom', 'api', name='source_type'), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('lineage_root_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['lineage_root_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_country'), 'sources', ['country'], unique=False)
    op.create_index(op.f('ix_sources_lineage_root_id'), 'sources', ['lineage_root_id'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('articles',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('locale_country', sa.String(length=2), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.Text(), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_is_published'), 'articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_articles_locale_country'), 'articles', ['locale_country'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_table('country_sources',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'source_id', name='uq_country_source')
    )
    op.create_index(op.f('ix_country_sources_country_code'), 'country_sources', ['country_code'], unique=False)
    op.create_table('event_conflicts',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_conflicts_event_id'), 'event_conflicts', ['event_id'], unique=False)
    op.create_table('event_facts',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['event_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_facts_event_id'), 'event_facts', ['event_id'], unique=False)
    op.create_table('source_health',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('source_reliability',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.Column('independence_weight', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('source_reports',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('canonical_url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('raw_text_if_permitted', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSED', 'DUPLICATE', 'REJECTED', 'FAILED', name='source_report_status'), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['source_reports.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url_hash', name='uq_source_report_canonical')
    )
    op.create_index('ix_source_reports_content_hash', 'source_reports', ['content_hash'], unique=False)
    op.create_index('ix_source_reports_published_at', 'source_reports', ['published_at'], unique=False)
    op.create_index(op.f('ix_source_reports_simhash'), 'source_reports', ['simhash'], unique=False)
    op.create_index(op.f('ix_source_reports_source_id'), 'source_reports', ['source_id'], unique=False)
    op.create_table('article_images',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('image_provider', sa.String(length=64), nullable=False),
    sa.Column('generation_id', sa.String(length=200), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('ephemeral_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_images_article_id'), 'article_images', ['article_id'], unique=False)
    op.create_table('article_sources',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('is_independent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['source_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'source_id', name='uq_article_source')
    )
    op.create_index(op.f('ix_article_sources_article_id'), 'article_sources', ['article_id'], unique=False)
    op.create_table('article_versions',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'version', name='uq_article_version')
    )
    op.create_index(op.f('ix_article_versions_article_id'), 'article_versions', ['article_id'], unique=False)
    op.create_table('event_reports',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['source_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'source_report_id', name='uq_event_report')
    )
    op.create_index(op.f('ix_event_reports_event_id'), 'event_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_reports_source_report_id'), 'event_reports', ['source_report_id'], unique=False)
    op.create_table('event_updates',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['source_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_updates_event_id'), 'event_updates', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_updates_event_id'), table_name='event_updates')
    op.drop_table('event_updates')
    op.drop_index(op.f('ix_event_reports_source_report_id'), table_name='event_reports')
    op.drop_index(op.f('ix_event_reports_event_id'), table_name='event_reports')
    op.drop_table('event_reports')
    op.drop_index(op.f('ix_article_versions_article_id'), table_name='article_versions')
    op.drop_table('article_versions')
    op.drop_index(op.f('ix_article_sources_article_id'), table_name='article_sources')
    op.drop_table('article_sources')
    op.drop_index(op.f('ix_article_images_article_id'), table_name='article_images')
    op.drop_table('article_images')
    op.drop_index(op.f('ix_source_reports_source_id'), table_name='source_reports')
    op.drop_index(op.f('ix_source_reports_simhash'), table_name='source_reports')
    op.drop_index('ix_source_reports_published_at', table_name='source_reports')
    op.drop_index('ix_source_reports_content_hash', table_name='source_reports')
    op.drop_table('source_reports')
    op.drop_table('source_reliability')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_event_facts_event_id'), table_name='event_facts')
    op.drop_table('event_facts')
    op.drop_index(op.f('ix_event_conflicts_event_id'), table_name='event_conflicts')
    op.drop_table('event_conflicts')
    op.drop_index(op.f('ix_country_sources_country_code'), table_name='country_sources')
    op.drop_table('country_sources')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_locale_country'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_published'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_lineage_root_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_country'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_country'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('countries')
    # ### end Alembic commands ###
