"""phase 3 event intelligence

Revision ID: 4634825a4b2d
Revises: 239a6ea1c6a4
Create Date: 2026-10-07 20:32:53.479110
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


revision: str = '4634825a4b2d'
down_revision: str | None = '239a6ea1c6a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_fact_sources',
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['event_facts.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['source_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'source_report_id', name='uq_fact_source')
    )
    op.create_index(op.f('ix_event_fact_sources_fact_id'), 'event_fact_sources', ['fact_id'], unique=False)
    op.create_index(op.f('ix_event_fact_sources_source_report_id'), 'event_fact_sources', ['source_report_id'], unique=False)
    op.add_column('event_facts', sa.Column('fact_key', sa.String(length=160), nullable=True))
    op.create_index(op.f('ix_event_facts_fact_key'), 'event_facts', ['fact_key'], unique=False)
    # Existing events predate these counters; default them to 0.
    op.add_column(
        'events',
        sa.Column('report_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'events',
        sa.Column('independent_source_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'events',
        sa.Column('conflict_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column('events', sa.Column('simhash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_events_simhash'), 'events', ['simhash'], unique=False)
    op.add_column('source_reports', sa.Column('event_type', sa.String(length=64), nullable=True))
    op.add_column('source_reports', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('source_reports', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_source_reports_event_type'), 'source_reports', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_reports_event_type'), table_name='source_reports')
    op.drop_column('source_reports', 'processed_at')
    op.drop_column('source_reports', 'embedding')
    op.drop_column('source_reports', 'event_type')
    op.drop_index(op.f('ix_events_simhash'), table_name='events')
    op.drop_column('events', 'simhash')
    op.drop_column('events', 'conflict_count')
    op.drop_column('events', 'independent_source_count')
    op.drop_column('events', 'report_count')
    op.drop_index(op.f('ix_event_facts_fact_key'), table_name='event_facts')
    op.drop_column('event_facts', 'fact_key')
    op.drop_index(op.f('ix_event_fact_sources_source_report_id'), table_name='event_fact_sources')
    op.drop_index(op.f('ix_event_fact_sources_fact_id'), table_name='event_fact_sources')
    op.drop_table('event_fact_sources')
    # ### end Alembic commands ###
